# Generated by Django 5.0.6 on 2024-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
    ]
