# Generated by Django 5.0.6 on 2024-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otp", "0002_alter_otp_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
