# Generated by Django 5.0.6 on 2024-07-02 04:12

import django.db.models.deletion
import paywallet.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=paywallet.storage_backends.PublicMediaStorage(),
                        upload_to="allergies/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy",
                "verbose_name_plural": "Allergies",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ar", models.CharField(max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=paywallet.storage_backends.PublicMediaStorage(),
                        upload_to="categories/",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_ar", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=paywallet.storage_backends.PublicMediaStorage(),
                        upload_to="products/",
                    ),
                ),
                ("allergies", models.ManyToManyField(blank=True, to="product.allergy")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "permissions": [
                    ("import_product", "Can import Products"),
                    ("export_product", "Can export Products"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
    ]
