# Generated by Django 4.2.5 on 2023-11-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="restriction",
            field=models.ManyToManyField(blank=True, to="product.dietaryrestriction"),
        ),
    ]
