# Generated by Django 4.2.5 on 2024-03-10 02:50

from django.db import migrations, models
import paywallet.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=paywallet.storage_backends.PublicMediaStorage(),
                upload_to="allergies/",
                verbose_name="Image",
            ),
        ),
    ]
