# Generated by Django 4.2.5 on 2024-03-10 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_allergy_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("import_product", "Can import Products"),
                    ("export_product", "Can export Products"),
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
