# Generated by Django 4.2.5 on 2023-11-05 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
