# Generated by Django 4.2.5 on 2024-03-17 01:45

from django.db import migrations, models
import paywallet.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=paywallet.storage_backends.PublicMediaStorage(),
                upload_to="categories/",
            ),
        ),
    ]
