# Generated by Django 4.2.5 on 2023-11-06 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="dietaryrestriction",
            options={
                "verbose_name": "Dietary Restriction",
                "verbose_name_plural": "Dietary Restrictions",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
