# Generated by Django 4.2.5 on 2023-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_rename_parent_category_parent_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
    ]
