# Generated by Django 4.2.5 on 2023-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_productdashboard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductDashboard",
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
    ]
