# Generated by Django 5.0.6 on 2024-07-02 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="updated_date",
            new_name="order_updated_date",
        ),
    ]
