# Generated by Django 5.0.6 on 2024-07-02 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="updated_date",
        ),
    ]
