# Generated by Django 5.0.6 on 2024-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
