# Generated by Django 5.0.6 on 2024-07-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_store", "0003_schoolorder_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
