# Generated by Django 4.2.5 on 2024-02-04 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("primary_email", models.CharField(max_length=100)),
                (
                    "school_admin",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "School Admin"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=100)),
                ("grade", models.IntegerField(default=0)),
                ("date_of_birth", models.DateField(default=None)),
                ("rfid", models.CharField(max_length=100, unique=True)),
                ("balance", models.FloatField(default=0)),
                (
                    "restrictions",
                    models.ManyToManyField(blank=True, to="product.dietaryrestriction"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="school.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("in_time", models.DateTimeField(auto_now_add=True)),
                ("out_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
            },
        ),
    ]
