# Generated by Django 5.0.6 on 2024-07-02 02:42

import django.db.models.deletion
import paywallet.storage_backends
import school.models.announcement
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "phone_number",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                (
                    "primary_email",
                    models.CharField(max_length=100, verbose_name="Primary Email"),
                ),
                (
                    "school_admin",
                    models.OneToOneField(
                        limit_choices_to={"groups__name": "School Admin"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="School Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_operator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator",
                "verbose_name_plural": "Operators",
            },
        ),
        migrations.CreateModel(
            name="Bracelet",
            fields=[
                (
                    "rfid",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="RFID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Bracelet Model"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="unassigned",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bracelet",
                "verbose_name_plural": "Bracelets",
                "permissions": [
                    ("import_bracelet", "Can import Bracelets"),
                    ("export_bracelet", "Can export Bracelets"),
                ],
                "unique_together": {("rfid", "school")},
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=paywallet.storage_backends.PublicMediaStorage(),
                        upload_to=school.models.announcement.Announcement.get_image_folder,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.CreateModel(
            name="SchoolAdministrator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "School Administrator",
                "verbose_name_plural": "School Administrators",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=100, verbose_name="Registration Number"
                    ),
                ),
                ("grade", models.IntegerField(default=0, verbose_name="Grade")),
                (
                    "date_of_birth",
                    models.DateField(default=None, verbose_name="Date of Birth"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=paywallet.storage_backends.PublicMediaStorage(),
                        upload_to="students/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "bracelet",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.bracelet",
                        verbose_name="Bracelet",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "unique_together": {("registration_number", "school")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("in_time", models.DateTimeField(auto_now_add=True)),
                ("out_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=100, verbose_name="Registration Number"
                    ),
                ),
                ("grade", models.IntegerField(default=0, verbose_name="Grade")),
                (
                    "bracelet",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.bracelet",
                        verbose_name="Bracelet",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "unique_together": {("registration_number", "school")},
            },
        ),
    ]
