# Generated by Django 4.2.5 on 2024-02-21 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "phone_number",
                    models.CharField(max_length=100, verbose_name="Phone Number"),
                ),
                (
                    "primary_email",
                    models.CharField(max_length=100, verbose_name="Primary Email"),
                ),
                (
                    "school_admin",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "School Admin"},
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="School Admin",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=100, verbose_name="Registration Number"
                    ),
                ),
                ("grade", models.IntegerField(default=0, verbose_name="Grade")),
                (
                    "date_of_birth",
                    models.DateField(default=None, verbose_name="Date of Birth"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "unique_together": {("registration_number", "school")},
            },
        ),
        migrations.CreateModel(
            name="Bracelet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Bracelet Model"),
                ),
                (
                    "rfid",
                    models.CharField(max_length=100, unique=True, verbose_name="RFID"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bracelet",
                "verbose_name_plural": "Bracelets",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("in_time", models.DateTimeField(auto_now_add=True)),
                ("out_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
            },
        ),
    ]
