# Generated by Django 5.0.6 on 2024-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracelet",
            name="rfid",
            field=models.CharField(
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="RFID",
            ),
        ),
    ]
