# Generated by Django 4.2.5 on 2023-11-04 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name_plural": "Attendance"},
        ),
    ]
