# Generated by Django 4.2.5 on 2024-03-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="rfid",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="RFID",
            ),
        ),
    ]
