# Generated by Django 4.2.5 on 2024-02-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_bracelet_student_teacher_bracelet"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="bracelet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="school.bracelet",
            ),
        ),
    ]
