# Generated by Django 4.2.5 on 2023-11-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="school.school",
            ),
        ),
    ]
