# Generated by Django 4.2.5 on 2024-03-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_student_rfid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="bracelet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="school.bracelet",
            ),
        ),
    ]
