# Generated by Django 4.2.5 on 2024-03-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_rename_student_id_attendance_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="bracelet",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="school.bracelet",
                verbose_name="Bracelet",
            ),
        ),
    ]
