# Generated by Django 4.2.5 on 2023-11-05 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_product_is_active_product_price_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="school",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
