# Generated by Django 4.2.5 on 2024-02-25 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_student_bracelet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="bracelet",
        ),
    ]
