# Generated by Django 4.2.5 on 2024-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_teacher_bracelet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracelet",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("deactivated", "Deactivated"),
                ],
                default="unassigned",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
