# Generated by Django 4.2.5 on 2024-03-08 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_alter_bracelet_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bracelet",
            options={
                "permissions": [
                    ("import_bracelet", "Can import"),
                    ("export_bracelet", "Can export"),
                ],
                "verbose_name": "Bracelet",
                "verbose_name_plural": "Bracelets",
            },
        ),
    ]
