# Generated by Django 4.2.5 on 2023-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_rename_school_id_student_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Attendance", "verbose_name_plural": "Attendance"},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "School", "verbose_name_plural": "Schools"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
