# Generated by Django 4.2.5 on 2024-02-27 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_student_bracelet"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bracelet",
            unique_together={("rfid", "school")},
        ),
    ]
