# Generated by Django 4.2.5 on 2024-02-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_alter_bracelet_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="bracelet",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="school.bracelet",
                unique=True,
                verbose_name="Bracelet",
            ),
        ),
    ]
