# Generated by Django 4.2.5 on 2024-03-10 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_schooladministrator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bracelet",
            options={
                "permissions": [
                    ("import_bracelet", "Can import Bracelets"),
                    ("export_bracelet", "Can export Bracelets"),
                ],
                "verbose_name": "Bracelet",
                "verbose_name_plural": "Bracelets",
            },
        ),
    ]
