# Generated by Django 4.2.5 on 2024-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_student_bracelet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="bracelet_status",
            field=models.BooleanField(default=False, verbose_name="Bracelet Status"),
        ),
    ]
