# Generated by Django 4.2.5 on 2024-03-01 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0011_alter_student_bracelet_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="bracelet_status",
        ),
    ]
