# Generated by Django 4.2.5 on 2024-03-02 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0013_bracelet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracelet",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="bracelet",
            name="status",
            field=models.CharField(
                choices=[("assigned", "Assigned"), ("unassigned", "Unassigned")],
                default="unassigned",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
