# Generated by Django 4.2.5 on 2024-03-12 02:25

from django.db import migrations, models
import paywallet.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0013_alter_school_school_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(
                default="students/default.jpg",
                storage=paywallet.storage_backends.PublicMediaStorage(),
                upload_to="students/",
                verbose_name="Image",
            ),
        ),
    ]
