# Generated by Django 4.2.5 on 2024-03-12 02:26

from django.db import migrations, models
import paywallet.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0014_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(
                storage=paywallet.storage_backends.PublicMediaStorage(),
                upload_to="students/",
                verbose_name="Image",
            ),
        ),
    ]
