# Generated by Django 4.2.5 on 2023-11-04 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracelet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rfid", models.CharField(max_length=100)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.IntegerField(default=0)),
                (
                    "bracelet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="wallet.bracelet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "credit"), ("debit", "debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bracelet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="wallet.bracelet",
                    ),
                ),
                (
                    "merchant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="cafe.cafe"
                    ),
                ),
            ],
        ),
    ]
