# Generated by Django 4.2.5 on 2024-02-04 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guardian", "0001_initial"),
        ("product", "0001_initial"),
        ("cafe", "0001_initial"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bracelet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rfid", models.CharField(max_length=100, unique=True)),
                ("balance", models.FloatField(default=0)),
                (
                    "restrictions",
                    models.ManyToManyField(blank=True, to="product.dietaryrestriction"),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="school.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bracelet",
                "verbose_name_plural": "Bracelets",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "credit"), ("debit", "debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bracelet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="wallet.bracelet",
                    ),
                ),
                (
                    "merchant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="PaymentRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("count_per_period", models.IntegerField(default=3)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Daily", "Daily"),
                            ("Monthly", "Monthly"),
                        ],
                        default="Weekly",
                        max_length=10,
                    ),
                ),
                (
                    "bracelet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.bracelet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Restriction",
                "verbose_name_plural": "Payment Restrictions",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("device_fcm_token", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="guardian_user",
                        to="guardian.guardian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="CategoryRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bracelet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.bracelet",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Restriction",
                "verbose_name_plural": "Category Restrictions",
            },
        ),
    ]
