# Generated by Django 4.2.5 on 2024-03-08 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="status",
            new_name="active",
        ),
    ]
