# Generated by Django 4.2.5 on 2024-03-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
