# Generated by Django 4.2.5 on 2023-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracelet",
            name="rfid",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
