# Generated by Django 4.2.5 on 2024-03-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0009_delete_dashboard"),
        ("wallet", "0002_rename_status_wallet_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="cafe.order",
            ),
        ),
    ]
