# Generated by Django 4.2.5 on 2023-11-05 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_alter_bracelet_rfid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="bracelet_id",
        ),
    ]
