# Generated by Django 4.2.5 on 2023-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_remove_wallet_bracelet_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
        migrations.AddField(
            model_name="bracelet",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
