# Generated by Django 4.2.5 on 2024-04-20 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("guardian", "0003_guardian_image"),
        ("wallet", "0003_transaction_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="guardian.guardian",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="wallet.wallet"
                    ),
                ),
            ],
        ),
    ]
