# Generated by Django 4.2.5 on 2023-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_dietaryrestriction_product_restriction"),
        ("wallet", "0004_delete_wallet_bracelet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracelet",
            name="restrictions",
            field=models.ManyToManyField(blank=True, to="product.dietaryrestriction"),
        ),
    ]
