# Generated by Django 4.2.5 on 2023-11-05 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0005_bracelet_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracelet",
            name="guardian_id",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Guardian"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
