# Generated by Django 4.2.5 on 2023-11-05 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_bracelet_guardian_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bracelet",
            old_name="guardian_id",
            new_name="guardian",
        ),
    ]
