# Generated by Django 4.2.5 on 2023-11-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_category_options"),
        ("wallet", "0007_rename_guardian_id_bracelet_guardian"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("count_per_period", models.IntegerField(default=3)),
                (
                    "bracelet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.bracelet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "bracelet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.bracelet",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
