# Generated by Django 4.2.5 on 2023-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_paymentrestriction_categoryrestriction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryrestriction",
            name="name",
        ),
        migrations.RemoveField(
            model_name="paymentrestriction",
            name="name",
        ),
        migrations.AddField(
            model_name="paymentrestriction",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Weekly", "Weekly"),
                    ("Daily", "Daily"),
                    ("Monthly", "Monthly"),
                ],
                default="Weekly",
                max_length=10,
            ),
        ),
    ]
