# Generated by Django 4.2.5 on 2023-11-06 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0009_remove_categoryrestriction_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="bracelet_id",
            new_name="bracelet",
        ),
    ]
