# Generated by Django 4.2.5 on 2023-11-06 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0010_rename_bracelet_id_transaction_bracelet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bracelet",
            options={"verbose_name": "Bracelet", "verbose_name_plural": "Bracelets"},
        ),
        migrations.AlterModelOptions(
            name="categoryrestriction",
            options={
                "verbose_name": "Category Restriction",
                "verbose_name_plural": "Category Restrictions",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrestriction",
            options={
                "verbose_name": "Payment Restriction",
                "verbose_name_plural": "Payment Restrictions",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
