# Generated by Django 4.2.5 on 2023-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0012_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="phone_number",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
