# Generated by Django 4.2.5 on 2024-03-02 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0014_alter_bracelet_school_alter_bracelet_status"),
        ("restriction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryrestriction",
            name="student",
        ),
        migrations.RemoveField(
            model_name="dietrestriction",
            name="student",
        ),
        migrations.RemoveField(
            model_name="paymentrestriction",
            name="student",
        ),
        migrations.RemoveField(
            model_name="productrestriction",
            name="student",
        ),
        migrations.AddField(
            model_name="categoryrestriction",
            name="bracelet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.bracelet",
            ),
        ),
        migrations.AddField(
            model_name="dietrestriction",
            name="bracelet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.bracelet",
            ),
        ),
        migrations.AddField(
            model_name="paymentrestriction",
            name="bracelet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.bracelet",
            ),
        ),
        migrations.AddField(
            model_name="productrestriction",
            name="bracelet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.bracelet",
            ),
        ),
    ]
