# Generated by Django 4.2.5 on 2024-03-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_student_rfid"),
        ("restriction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryrestriction",
            name="bracelet",
        ),
        migrations.RemoveField(
            model_name="dietrestriction",
            name="bracelet",
        ),
        migrations.RemoveField(
            model_name="paymentrestriction",
            name="bracelet",
        ),
        migrations.RemoveField(
            model_name="productrestriction",
            name="bracelet",
        ),
        migrations.AddField(
            model_name="categoryrestriction",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
        ),
        migrations.AddField(
            model_name="dietrestriction",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
        ),
        migrations.AddField(
            model_name="paymentrestriction",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
        ),
        migrations.AddField(
            model_name="productrestriction",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
            ),
        ),
    ]
