# Generated by Django 4.2.5 on 2024-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("restriction", "0002_remove_categoryrestriction_bracelet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrestriction",
            name="product",
        ),
        migrations.AddField(
            model_name="productrestriction",
            name="product",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
    ]
