# Generated by Django 4.2.5 on 2024-03-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_options"),
        ("restriction", "0005_remove_productrestriction_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrestriction",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
    ]
