# Generated by Django 4.2.5 on 2024-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restriction", "0008_productsrestriction_delete_productrestriction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryrestriction",
            name="count_per_period",
        ),
        migrations.RemoveField(
            model_name="paymentrestriction",
            name="count_per_period",
        ),
        migrations.RemoveField(
            model_name="productsrestriction",
            name="count_per_period",
        ),
        migrations.AddField(
            model_name="categoryrestriction",
            name="total_per_period",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="paymentrestriction",
            name="total_per_period",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="productsrestriction",
            name="total_per_period",
            field=models.IntegerField(default=3),
        ),
    ]
