# Generated by Django 4.2.5 on 2024-03-10 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guardian", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guardian",
            name="device_fcm_token",
        ),
    ]
