# Generated by Django 4.2.5 on 2024-03-10 04:09

from django.db import migrations, models
import paywallet.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("guardian", "0002_remove_guardian_device_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=paywallet.storage_backends.PublicMediaStorage,
                upload_to="guardian/",
            ),
        ),
    ]
