# Generated by Django 4.2.5 on 2023-11-04 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solditems",
            old_name="originalPrice",
            new_name="original_price",
        ),
        migrations.RenameField(
            model_name="solditems",
            old_name="sellingPrice",
            new_name="selling_price",
        ),
    ]
