# Generated by Django 4.2.5 on 2024-03-05 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
    ]
