# Generated by Django 4.2.5 on 2024-02-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cafe_id",
            new_name="cafe",
        ),
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.AddField(
            model_name="inventory",
            name="product_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cafe",
            unique_together={("name", "address")},
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product_code", "cafe")},
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="currency",
        ),
    ]
