# Generated by Django 4.2.5 on 2023-11-04 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0002_sale_solditems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solditems",
            name="sale_id",
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
        migrations.DeleteModel(
            name="SoldItems",
        ),
    ]
