# Generated by Django 4.2.5 on 2024-03-02 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cafe", "0002_rename_cafe_id_order_cafe_remove_order_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafe",
            old_name="vendor_admin",
            new_name="admin",
        ),
        migrations.RemoveField(
            model_name="cafe",
            name="vendor_operators",
        ),
        migrations.AddField(
            model_name="cafe",
            name="operators",
            field=models.ManyToManyField(
                limit_choices_to={
                    "groups__name__in": ["Vendor Admin", "Vendor Operator"]
                },
                related_name="vendor_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
