# Generated by Django 4.2.5 on 2024-03-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("cafe", "0002_remove_order_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                to="product.product",
            ),
        ),
    ]
