# Generated by Django 4.2.5 on 2023-11-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("cafe", "0003_remove_solditems_sale_id_delete_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="product.product"
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
