# Generated by Django 4.2.5 on 2023-11-06 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0004_alter_inventory_product_id_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total", models.FloatField()),
                ("currency", models.CharField(default="KWD", max_length=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("points", "Points"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "cafe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("original_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                ("currency", models.CharField(default="KWD", max_length=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cafe.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
    ]
