# Generated by Django 4.2.5 on 2023-11-06 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
    ]
