# Generated by Django 4.2.5 on 2023-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0007_rename_cafe_id_inventory_cafe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cafe.inventory",),
        ),
    ]
