# Generated by Django 4.2.5 on 2024-03-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0013_alter_school_school_admin"),
        ("cafe", "0007_remove_vendoradmin_cafe"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="school",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
            ),
        ),
    ]
