# Generated by Django 4.2.5 on 2024-03-12 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0008_cafe_school"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
