# Generated by Django 4.2.5 on 2024-01-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0010_rename_name_operator_first_name_operator_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
