# Generated by Django 4.2.5 on 2024-01-21 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0011_alter_operator_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="password",
        ),
    ]
