# Generated by Django 4.2.5 on 2024-01-21 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0012_remove_operator_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="email",
        ),
        migrations.RemoveField(
            model_name="operator",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="operator",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="operator",
            name="role",
        ),
    ]
